add allure report #4
qaivanpleten/sp_learning pull request #13
Opened 2017-10-03 04:50 UTC by qaivanpleten

@extsoft please check

2017-10-03 18:47 UTC, extsoft requested changes
@qaivanpleten please take a look for my comments.

2017-10-03 18:47 UTC, extsoft commented on README.md
> +
@qaivanpleten please use proper fromatting. it looks not so good - https://github.com/qaivanpleten/sp_learning/blob/863e33ef11c291a9708b9bd47d8fd7be6850cf5d/README.md

2017-10-03 18:47 UTC, extsoft commented on README.md
>  pytest src/modules/example/test/
`py.test` instead of `pytyst`.

2017-10-03 18:47 UTC, extsoft commented on README.md
> +py.test --alluredir=report C:\Users\Владелец\PycharmProjects\sp_learning\sp_at\test_cases\test_why_page.py
Use relative path here.

2017-10-04 08:06 UTC, qaivanpleten commented
@extsoft  
Fixed

2017-10-05 10:02 UTC, extsoft approved these changes

2017-10-05 10:02 UTC, merged