page object for Integration_page
qaivanpleten/sp_learning pull request #21
Opened 2017-10-23 06:29 UTC by qaivanpleten

Changed test for Integration page using page object methodology. Created integration_page file (page object) and changed test_integration_page.py
#18

2017-10-24 14:22 UTC, extsoft requested changes
@qaivanpleten please take a look at the comments below.

2017-10-24 14:22 UTC, extsoft commented on sp_at/pages/integration_page.py
> +class SlowIntegrationPage(IntegrationPage):
You don't need this class if you don't use it.

2017-10-24 14:22 UTC, extsoft commented on sp_at/pages/integration_page.py
> +                return True
This line says that body is present if the title is displayed. I'm not sure that this is correct. I suppose you need to return `true` only if all elements are displayed.

2017-10-24 14:22 UTC, extsoft commented on sp_at/test_cases/test_integration_page.py
>  from sp_at.elements.main_page_elements import MainPageElements
spare import

2017-10-24 14:22 UTC, extsoft commented on sp_at/test_cases/test_integration_page.py
>  from sp_at.actions.general_actions import GeneralActions
spare import

2017-10-25 05:51 UTC, qaivanpleten commented
@extsoft 
The issues are fixed. Please check

2017-10-25 07:13 UTC, extsoft approved these changes

2017-10-25 07:13 UTC, merged